spring:
  application:
    name: library
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpa_library
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
  com.jpa.library: debug
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: #젠킨스에서 설정
    username: #젠킨스에서 설정
    password: #젠킨스에서 설정
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  com.jpa.library: debug
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: #젠킨스에서 설정
    username: #젠킨스에서 설정
    password: #젠킨스에서 설정
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  com.jpa.library: debug