spring:
  application:
    name: library
  profiles:
    default: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/jpa_library
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  com.jpa.library: debug